// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.174.0
//   protoc               v3.21.12
// source: Agate.proto

/* eslint-disable */

export const protobufPackage = "obiba.agate";

export enum KeyType {
  KEY_PAIR = "KEY_PAIR",
  CERTIFICATE = "CERTIFICATE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RealmStatus {
  INACTIVE = "INACTIVE",
  ACTIVE = "ACTIVE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface SessionDto {
  username: string;
  role: string;
  realm: string;
}

export interface AuthorizationDto {
  id: string;
  username: string;
  application: string;
  code: string;
  redirectURI?: string | undefined;
  scopes: string[];
  timestamps?: TimestampsDto | undefined;
  applicationName?: string | undefined;
}

export interface TicketDto {
  id: string;
  timestamps?: TimestampsDto | undefined;
  username: string;
  remembered: boolean;
  events: TicketDto_Event[];
  expires?: string | undefined;
  authorization?: AuthorizationDto | undefined;
}

export interface TicketDto_Event {
  application?: string | undefined;
  action: string;
  time: string;
}

export interface TimestampsDto {
  created?: string | undefined;
  lastUpdate?: string | undefined;
}

export interface AttributeConfigurationDto {
  name: string;
  required: boolean;
  type: string;
  values: string[];
  description?: string | undefined;
}

export interface LocalizedStringDto {
  lang: string;
  value?: string | undefined;
}

export interface ConfigurationDto {
  name: string;
  domain?:
    | string
    | undefined;
  /** hours */
  shortTimeout: number;
  /** hours */
  longTimeout: number;
  userAttributes: AttributeConfigurationDto[];
  /** hours */
  inactiveTimeout: number;
  publicUrl?: string | undefined;
  joinWithUsername: boolean;
  version?: string | undefined;
  style?: string | undefined;
  languages: string[];
  translations: LocalizedStringDto[];
  portalUrl?: string | undefined;
  joinPageEnabled: boolean;
  joinWhitelist?: string | undefined;
  joinBlacklist?: string | undefined;
  enforced2FAStrategy: string;
}

export interface PublicConfigurationDto {
  name: string;
  languages: string[];
  joinWithUsername: boolean;
  userAttributes: AttributeConfigurationDto[];
  publicUrl?: string | undefined;
}

export interface AttributeDto {
  name: string;
  value?: string | undefined;
}

export interface UserCreateFormDto {
  user: UserDto | undefined;
  password?: string | undefined;
}

export interface UserDto {
  id?: string | undefined;
  name: string;
  realm: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email: string;
  attributes: AttributeDto[];
  role: string;
  status: string;
  groups: string[];
  applications: string[];
  timestamps?: TimestampsDto | undefined;
  groupApplications: GroupApplicationDto[];
  lastLogin?: string | undefined;
  preferredLanguage?: string | undefined;
  accountUrl?: string | undefined;
  otpEnabled?: boolean | undefined;
}

export interface UserSummaryDto {
  id?: string | undefined;
  name: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email: string;
}

export interface GroupApplicationDto {
  group: string;
  application: string;
}

export interface GroupDto {
  id?: string | undefined;
  name: string;
  description?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  applications: string[];
  users: UserSummaryDto[];
}

export interface ApplicationDto {
  id?: string | undefined;
  name: string;
  key?: string | undefined;
  description?: string | undefined;
  timestamps?: TimestampsDto | undefined;
  redirectURI?: string | undefined;
  scopes: ApplicationDto_ScopeDto[];
  autoApproval?: boolean | undefined;
}

export interface ApplicationDto_ScopeDto {
  name: string;
  description?: string | undefined;
}

export interface ConfirmForm {
  username: string;
  key: string;
  password: string;
}

export interface KeyDto {
  alias: string;
  certificate: string;
  keyType: KeyType;
}

export interface KeyForm {
  alias?: string | undefined;
  privateForm?: PrivateKeyForm | undefined;
  privateImport?: string | undefined;
  publicForm?: PublicKeyForm | undefined;
  publicImport?: string | undefined;
  certificateFile?: string | undefined;
  keyType: KeyType;
}

export interface PrivateKeyForm {
  algo: string;
  size: number;
}

export interface PublicKeyForm {
  name: string;
  organizationalUnit: string;
  organization: string;
  locality: string;
  state: string;
  country: string;
}

export interface RealmConfigDto {
  id?: string | undefined;
  name: string;
  title: LocalizedStringDto[];
  description: LocalizedStringDto[];
  groups: string[];
  type: string;
  forSignup?: boolean | undefined;
  status?: RealmStatus | undefined;
  content: string;
  users: UserSummaryDto[];
  userCount?: number | undefined;
  userInfoMappings: RealmConfigDto_UserInfoMappingDto[];
  publicUrl?: string | undefined;
  domain?: string | undefined;
}

export interface RealmConfigDto_UserInfoMappingDto {
  key: string;
  value: string;
}

export interface RealmConfigSummaryDto {
  id?: string | undefined;
  name: string;
  type: string;
  title: LocalizedStringDto[];
  description: LocalizedStringDto[];
  status?: RealmStatus | undefined;
  userCount?: number | undefined;
}
