#! /usr/bin/env python
#
import argparse

import agate.rest

def add_agate_arguments(parser):
    """
    Add Agate access arguments
    """
    parser.add_argument('--agate', '-ag', required=False, default='http://localhost:8081', help='Agate server base url (default: http://localhost:8081)')
    parser.add_argument('--user', '-u', required=False, help='User name')
    parser.add_argument('--password', '-p', required=False, help='User password')
    parser.add_argument('--ssl-cert', '-sc', required=False, help='Certificate (public key) file')
    parser.add_argument('--ssl-key', '-sk', required=False, help='Private key file')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')


def add_subcommand(name, help, add_args_func, default_func):
    """
    Make a sub-parser, add default arguments to it, add sub-command arguments and set the sub-command callback function.
    """
    subparser = subparsers.add_parser(name, help=help)
    add_agate_arguments(subparser)
    add_args_func(subparser)
    subparser.set_defaults(func=default_func)


# Parse arguments
parser = argparse.ArgumentParser(description='Agate command line.')
subparsers = parser.add_subparsers(title='sub-commands',
                                   help='Available sub-commands. Use --help option on the sub-command '
                                        'for more details.')

# Add subcommands
add_subcommand('rest', 'Request directly the Agate REST API, for advanced users.', agate.rest.add_arguments,
               agate.rest.do_command)

# Execute selected command
args = parser.parse_args()
args.func(args)
